name: Deployment - Staging
run-name: Deployment - Staging
on: [workflow_dispatch]
concurrency: deployment-staging
# permissions:
#   id-token: write
#   contents: read
permissions: read-all
jobs:
  deployment:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh run list -w master.yml -b master -L 1
          gh run list -w master.yml -b master -L 1 --json status
          gh run list -w master.yml -b master -L 1 --json status | jq -e -r '.[0].status == "completed"'
      - run: echo 'deployed'
