name: Acceptance tests
run-name: Acceptance tests
on:
  workflow_dispatch:
    inputs:
      force_deployment:
        description: "Force deployment regardless of failure on master workflow"
        type: boolean
        default: false

concurrency: deployment-staging
permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  # deployment:
  #   name: Deploy on staging
  #   uses: ./.github/workflows/shared-deployment.yml
  #   with:
  #     environment: staging
  #     ignore_status_check: ${{ inputs.force_deployment }}
  #   secrets: inherit

  test:
    name: Master workflow status
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test push
        run: |
          echo 'asdf' > CHANGELOG.md
          git config --global user.email "mark@growthbox.com.au"
          git config --global user.name "Mark"
          git add CHANGELOG.md && git commit -m "[skip ci] Release ${version_number}" && git push git@github.com:mark-onenetwork/test.git master
