name: Deployment - Staging
run-name: Deployment - Staging
on: 
  workflow_dispatch:
    inputs:
      force_deployment:
        description: "Force deployment regardless of failure on master workflow"
        type: boolean
        default: false
concurrency: deployment-staging
# permissions:
#   id-token: write
#   contents: read
permissions: read-all
jobs:
  deployment:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Hello Step
        run: echo "Hello ${{ github.event.inputs.force_deployment }}"
      - name: test
        if: github.event.inputs.force_deployment == true
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh run list -w master.yml -b master -L 10
          gh run list -w master.yml -b master -L 1 --json status,conclusion,displayTitle
          gh run list -w master.yml -b master -L 1 --json status | jq -e -r '.[0].conslusion == "success"'
      - run: echo 'deployed'
