name: CRM Cron Jobs
run-name: CRM Cron Jobs
on:
  push:
  # schedule:
  #   - cron: '0 9 * * 3'
  #   - cron: '2 9 * * 3'
  #   - cron: '4 9 * * 3'
    # - cron: '6 9 * * 3'
    # - cron: '8 9 * * 3'

jobs:
  next-adss:
    name: CSV files for ADSS next
    # if: github.event.schedule == '0 9 * * 3'
    runs-on: ubuntu-latest
    uses: ./.github/workflows/shared-csv-export.yml
    with:
      environment: next
      brand: adss
    secrets: inherit

  next-mp:
    name: CSV files for MP next
    if: github.event.schedule == '2 9 * * 3'
    runs-on: ubuntu-latest
    uses: ./.github/workflows/shared-csv-export.yml
    with:
      environment: next
      brand: mp
    secrets: inherit

  next-sealink:
    name: CSV files for Sealink next
    if: github.event.schedule == '4 9 * * 3'
    runs-on: ubuntu-latest
    uses: ./.github/workflows/shared-csv-export.yml
    with:
      environment: next
      brand: sealink
    secrets: inherit

  # next-cccsyd:
  #   name: CSV files for CCCSYD next
  #   if: github.event.schedule == '6 9 * * 3'
  #   runs-on: ubuntu-latest
  #   uses: ./.github/workflows/shared-csv-export.yml
  #   with:
  #     environment: next
  #     brand: cccsyd
  #   secrets: inherit

  # next-jackson:
  #   name: CSV files for The Jackson next
  #   if: github.event.schedule == '8 9 * * 3'
  #   runs-on: ubuntu-latest
  #   uses: ./.github/workflows/shared-csv-export.yml
  #   with:
  #     environment: next
  #     brand: jackson
  #   secrets: inherit
