name: Manual CSV Export
run-name: Manual CSV Export
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select an environment'
        type: choice
        required: true
        default: 'next'
        options:
          - next
          - production
      brand:
        description: 'Select a brand'
        type: choice
        required: true
        default: 'cccsyd'
        options:
          - adss
          - mp
          - sealink
          - cccsyd
          - jackson

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print selected options
        run: |
          echo "Selected environment: ${{ github.event.inputs.environment }}"
          echo "User message: ${{ github.event.inputs.brand }}"
  export:
    name: Export CSV
    uses: ./.github/workflows/shared-csv-export.yml
    with:
      environment: ${{ inputs.environment }}
      brand: ${{ inputs.brand }}
    secrets: inherit
