name: Manual CSV Export
run-name: Manual CSV Export
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select an environment'
        required: true
        default: 'next'
        options:
          - next
          - production
      brand:
        description: 'Select a brand'
        required: true
        default: 'next'
        options:
          - adss
          - mp
          - sealink
          - cccsyd
          - jackson

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print selected options
        run: |
          echo "Selected environment: ${{ github.event.inputs.environment }}"
          echo "User message: ${{ github.event.inputs.brand }}"
  # deployment:
  #   name: Deploy on staging
  #   uses: ./.github/workflows/shared-deployment.yml
  #   with:
  #     environment: staging
  #     ignore_status_check: ${{ inputs.force_deployment }}
  #   secrets: inherit

  # test:
  #   name: Master workflow status
  #   runs-on: ubuntu-latest
  #   needs: [deployment]
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: test push
  #       run: |
  #         echo 'asdf' > CHANGELOG.md
  #         git config --global user.email "mark@growthbox.com.au"
  #         git config --global user.name "Mark"
  #         # git add CHANGELOG.md && git commit -m "11[skip ci] Release ${version_number}" && git push https://github.com/mark-onenetwork/test.git master
