name: Manual CSV Export
run-name: Manual CSV Export
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select an environment'
        type: choice
        required: true
        default: 'next'
        options:
          - next
          - production
      brand:
        description: 'Select a brand'
        type: choice
        required: true
        default: 'cccsyd'
        options:
          - adss
          - mp
          - sealink
          - cccsyd
          - jackson

jobs:
  export-csv:
    name: Export CSV
    uses: ./.github/workflows/shared-csv-export.yml
    with:
      environment: ${{ inputs.environment }}
      brand: ${{ inputs.brand }}
    secrets: inherit

