name: Master
run-name: Master
on: [push]
concurrency: master
permissions: read-all
jobs:
  default:
    name: Default
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls -alh
      - uses: actions/setup-node@v3
        with:
          node-version-file: ../.tool-versions
      - run: node --version
      - run: ls -alh
