name: Master
run-name: Master
on: [push]
concurrency: master
permissions: read-all
jobs:
  default:
    name: Default
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: node --version
