name: Reusable workflow for CSV export

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      brand:
        required: true
        type: string

env:
  LOCAL_FILES_DIR: /tmp/csv-files

  NEXT_REMOTE_FILES_DIR: /Import/mcp_catalog_testing
  NEXT_ADSS_PRODUCT_URL: https://adss-next.travellink.com.au/ecom/api/v1/studio_catalog/products
  NEXT_MP_PRODUCT_URL: https://mp-next.travellink.com.au/ecom/api/v1/studio_catalog/products
  NEXT_SEALINK_PRODUCT_URL: https://sealink-next.travellink.com.au/ecom/api/v1/studio_catalog/products
  NEXT_SEALINK_CATEGORY_URL: https://sealink-next.travellink.com.au/ecom/api/v1/studio_catalog/categories
  NEXT_CCCSYD_PRODUCT_URL: https://cccsydney-cms-next.travellink.com.au/ecom/api/v1/studio_catalog/products
  NEXT_JACKSON_PRODUCT_URL: https://thejackson-next.travellink.com.au/ecom/api/v1/studio_catalog/products

  PROD_REMOTE_FILES_DIR: /Import/mcp_catalog
  PROD_ADSS_PRODUCT_URL: https://www.adelaidesightseeing.com.au/ecom/api/v1/studio_catalog/products
  PROD_MP_PRODUCT_URL: https://www.murrayprincess.com.au/ecom/api/v1/studio_catalog/products
  PROD_SEALINK_PRODUCT_URL: https://www.sealink.com.au/ecom/api/v1/studio_catalog/products
  PROD_SEALINK_CATEGORY_URL: https://www.sealink.com.au/ecom/api/v1/studio_catalog/categories
  PROD_CCCSYD_PRODUCT_URL: https://www.captaincook.com.au/ecom/api/v1/studio_catalog/products
  PROD_JACKSON_PRODUCT_URL: https://www.thejackson.com.au/ecom/api/v1/studio_catalog/products

jobs:
  export-csv:
    name: Export CSV
    runs-on: ubuntu-latest
    steps:
      - name: Set the URL for the BU
        run: |
          if [ "${{ inputs.environment }}" == "next" ]; then
            if [ "${{ inputs.brand }}" == "adss" ]; then
              echo "URL=${{ env.NEXT_ADSS_PRODUCT_URL }}" >> $GITHUB_ENV
            elif [ "${{ inputs.brand }}" == "mp" ]; then
              echo "URL=${{ env.NEXT_MP_PRODUCT_URL }}" >> $GITHUB_ENV
            elif [ "${{ inputs.brand }}" == "sealink" ]; then
              echo "URL=${{ env.NEXT_SEALINK_PRODUCT_URL }}" >> $GITHUB_ENV
            elif [ "${{ inputs.brand }}" == "cccsyd" ]; then
              echo "URL=${{ env.NEXT_CCCSYD_PRODUCT_URL }}" >> $GITHUB_ENV
            elif [ "${{ inputs.brand }}" == "jackson" ]; then
              echo "URL=${{ env.NEXT_JACKSON_PRODUCT_URL }}" >> $GITHUB_ENV
            fi
          else
            if [ "${{ inputs.brand }}" == "adss" ]; then
              echo "URL=${{ env.PROD_ADSS_PRODUCT_URL }}" >> $GITHUB_ENV
            elif [ "${{ inputs.brand }}" == "mp" ]; then
              echo "URL=${{ env.PROD_MP_PRODUCT_URL }}" >> $GITHUB_ENV
            elif [ "${{ inputs.brand }}" == "sealink" ]; then
              echo "URL=${{ env.PROD_SEALINK_PRODUCT_URL }}" >> $GITHUB_ENV
            elif [ "${{ inputs.brand }}" == "cccsyd" ]; then
              echo "URL=${{ env.PROD_CCCSYD_PRODUCT_URL }}" >> $GITHUB_ENV
            elif [ "${{ inputs.brand }}" == "jackson" ]; then
              echo "URL=${{ env.PROD_JACKSON_PRODUCT_URL }}" >> $GITHUB_ENV
            fi
          fi

      - name: Download CSV files
        run: |
          mkdir -p $LOCAL_FILES_DIR
          curl -o "$LOCAL_FILES_DIR/product-$(date +'%Y-%m-%d_%H-%M-%S').csv" $URL

      - name: Upload CSV files to next SFTP
        if: inputs.environment == 'next'
        uses: wangyucode/sftp-upload-action@v2.0.2
        with:
          host: ${{ vars.CRM_SFTP_TESTING_HOST }}
          username: ${{ secrets.CRM_SFTP_TESTING_USERNAME }}
          password: ${{ secrets.CRM_SFTP_TESTING_PASSWORD }}
          localDir: '${{ env.LOCAL_FILES_DIR }}/'
          remoteDir: '${{ env.NEXT_REMOTE_FILES_DIR }}'

      - name: Upload CSV files to production SFTP
        if: inputs.environment == 'production'
        uses: wangyucode/sftp-upload-action@v2.0.2
        with:
          host: ${{ vars.CRM_SFTP_PRODUCTION_HOST }}
          username: ${{ secrets.CRM_SFTP_PRODUCTION_USERNAME }}
          password: ${{ secrets.CRM_SFTP_PRODUCTION_PASSWORD }}
          localDir: '${{ env.LOCAL_FILES_DIR }}/'
          remoteDir: '${{ env.PROD_REMOTE_FILES_DIR }}'
